# For versions before 1.9.0 use apps/v1
apiVersion: apps/v1
kind: Deployment

# Data that helps  uniquely identify the object (using name, UID and namespace)
metadata:
  name: nginx
  labels:
    app: nginx

# What state you desire for the object
spec:
  # Tells the deployment to run 3 pods matching the template
  replicas: 1

  # The selector field defines how the deployment finds which pod to manage
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      # Labels are used as identifying attributes for objects such as pods and replication controller.
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: 120761001082.dkr.ecr.us-east-2.amazonaws.com/my-repo:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  # Private Load Balancer
  name: internal-springboot-service
  # In order to configure load balancers to provide custom configuration we can use Kubernetes annotations
  annotations:
    # Defines type of load balancer like Network LB or Classic LB
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # Define for cross zone load balancing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    # Defines whether Public or Private Load Balancer used. This case we use Private LB.
    # if we don't specify this by default it will create Public LB.
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: springboot-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  # Public Load Balancer
  name: external-springboot-service
  # In order to configure load balancers to provide custom configuration we can use Kubernetes annotations
  annotations:
    # Defines type of load balancer like Network LB or Classic LB
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # Define for cross zone load balancing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: springboot-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
