FROM adoptopenjdk/openjdk11:alpine-jre
ADD target/springboot-angular-kubernetes-0.0.1-SNAPSHOT.jar springboot-angular-kubernetes-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springboot-angular-kubernetes-0.0.1-SNAPSHOT.jar"]
