FROM openjdk:11
ADD target/springboot-angular-kubernetes-0.0.1-SNAPSHOT.jar springboot-angular-kubernetes-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "springboot-angular-kubernetes-0.0.1-SNAPSHOT.jar"]


